Envolti Teste - Danielle/Malwee/Malwee/Controllers/EstatisticasController.cs
using Malwee.Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Malwee.Controllers
{
    public class EstatisticasController : Controller
    {
        // GET: Estatisticas
        // NÃO É NECESSARIO ESTÁ LOGADO, PORTANTO NÃO HERDA O BASECONTROLLER

            //INSTANCIA O DAO, ONDE É COLOCADO AS QUERYS PARA OS RELATORIOSS
        EstatisticaDAO Dao = new EstatisticaDAO();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ClienteMaisGastaramMes()
        {
            //BUSCA TODOS OS CLIENTES ORDENANDO POR MÊS
            var SelecionarClientesPorMes = Dao.SelecionarClientesPorMes().ToList();
            //janeiro 
            ViewBag.Janeiro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 1).Take(3).ToList();
            //fevereiro
            ViewBag.Fevereiro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 2).Take(3).ToList();
            //marco
            ViewBag.Marco = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 3).Take(3).ToList();
            //Abril
            ViewBag.Abril = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 4).Take(3).ToList();
            //Maio
            ViewBag.Maio = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 5).Take(3).ToList();
            //Junho
            ViewBag.Junho = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 6).Take(3).ToList();
            //Julho
            ViewBag.Julho = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 7).Take(3).ToList();
            //Agosto
            ViewBag.Agosto = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 8).Take(3).ToList();
            //Setembro
            ViewBag.Setembro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 9).Take(3).ToList();
            //Outubro
            ViewBag.Outubro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 10).Take(3).ToList();
            //Novembro
            ViewBag.Novembro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 11).Take(3).ToList();
            //Dezembro
            ViewBag.Dezembro = Dao.SelecionarClientesPorMes().Where(c => c.Mes == 12).Take(3).ToList();


            return View();
        }
       
        public ActionResult FornecedorSemAtendimentoNoMes()
        {

            //janeiro 
            ViewBag.Janeiro = Dao.FornecedoresSemAtendimeto(1).ToList();
            //fevereiro
            ViewBag.Fevereiro = Dao.FornecedoresSemAtendimeto(2).ToList();
            //marco
            ViewBag.Marco = Dao.FornecedoresSemAtendimeto(3).ToList();
            //Abril
            ViewBag.Abril = Dao.FornecedoresSemAtendimeto(4).ToList();
            //Maio
            ViewBag.Maio = Dao.FornecedoresSemAtendimeto(5).ToList();
            //Junho
            ViewBag.Junho = Dao.FornecedoresSemAtendimeto(6).ToList();
            //Julho
            ViewBag.Julho = Dao.FornecedoresSemAtendimeto(7).ToList();
            //Agosto
            ViewBag.Agosto = Dao.FornecedoresSemAtendimeto(8).ToList();
            //Setembro
            ViewBag.Setembro = Dao.FornecedoresSemAtendimeto(9).ToList();
            //Outubro
            ViewBag.Outubro = Dao.FornecedoresSemAtendimeto(10).ToList();
            //Novembro
            ViewBag.Novembro = Dao.FornecedoresSemAtendimeto(11).ToList();
            //Dezembro
            ViewBag.Dezembro = Dao.FornecedoresSemAtendimeto(12).ToList();


            return View();
        }
    }
}

Envolti Teste - Danielle/Malwee/Malwee/Views/Estatisticas/ClienteMaisGastaramMes.cshtml
@{
    var cont = 0;    
}

<h2>ESTATÍSTICAS</h2>
<h1>Os 3 clientes que mais gastaram em serviços por mês </h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Mês</th>
            <th>Cliente</th>
            <th>Valor</th>
        </tr>
    </thead>
    <tbody>
        <!-- REGISTRO DO MES DE JANEIRO -->
        @{
            if (ViewBag.Janeiro.Count == 0)
            {
                <tr>
                    <td align="center">JANEIRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Janeiro.Count; i++)
            {
                var total = ViewBag.Janeiro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JANEIRO</td>
                    }
                    <td>@ViewBag.Janeiro[i].Cliente</td>
                    <td>@ViewBag.Janeiro[i].Valor</td>
                </tr>
                cont++;
            }
        }

        <!-- REGISTRO DO MES DE FEVEREIRO -->
        @{
            if (ViewBag.Fevereiro.Count == 0)
            {
                <tr>
                    <td align="center">FEVEREIRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }

            for (int i = 0; i < ViewBag.Fevereiro.Count; i++)
            {
                var total = ViewBag.Fevereiro.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">FEVEREIRO</td>
                    }
                    <td>@ViewBag.Fevereiro[i].Cliente</td>
                    <td>@ViewBag.Fevereiro[i].Valor</td>
                </tr>
                cont++;
            }
        }

        <!-- REGISTRO DO MES DE MARCO -->

        @{ if (ViewBag.Marco.Count == 0)
            {
                <tr>
                    <td align="center">MARÇO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Marco.Count; i++)
            {
                var total = ViewBag.Marco.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">MARÇO</td>
                    }
                    <td>@ViewBag.Marco[i].Cliente</td>
                    <td>@ViewBag.Marco[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Abril -->

        @{ if (ViewBag.Abril.Count == 0)
            {
                <tr>
                    <td align="center">ABRIL</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Abril.Count; i++)
            {
                var total = ViewBag.Abril.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total;" align="center">ABRIL</td>
                    }
                    <td>@ViewBag.Abril[i].Cliente</td>
                    <td>@ViewBag.Abril[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE MAIO -->

        @{ if (ViewBag.Maio.Count == 0)
            {
                <tr>
                    <td align="center">MAIO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Maio.Count; i++)
            {
                var total = ViewBag.Maio.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">MAIO</td>
                    }
                    <td>@ViewBag.Maio[i].Cliente</td>
                    <td>@ViewBag.Maio[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE JUNHO -->

        @{ if (ViewBag.Junho.Count == 0)
            {
                <tr>
                    <td align="center">JUNHO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Junho.Count; i++)
            {
                var total = ViewBag.Junho.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JUNHO</td>
                    }
                    <td>@ViewBag.Junho[i].Cliente</td>
                    <td>@ViewBag.Junho[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Julho -->

        @{ if (ViewBag.Julho.Count == 0)
            {
                <tr>
                    <td align="center">JULHO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Julho.Count; i++)
            {
                var total = ViewBag.Julho.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JULHO</td>
                    }
                    <td>@ViewBag.Julho[i].Cliente</td>
                    <td>@ViewBag.Julho[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE MARCO -->

        @{ if (ViewBag.Agosto.Count == 0)
            {
                <tr>
                    <td align="center">AGOSTO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Agosto.Count; i++)
            {
                var total = ViewBag.Agosto.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">AGOSTO</td>
                    }
                    <td>@ViewBag.Agosto[i].Cliente</td>
                    <td>@ViewBag.Agosto[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Setembro -->

        @{ if (ViewBag.Setembro.Count == 0)
            {
                <tr>
                    <td align="center">SETEMBRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Setembro.Count; i++)
            {
                var total = ViewBag.Setembro.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">SETEMBRO</td>
                    }
                    <td>@ViewBag.Setembro[i].Cliente</td>
                    <td>@ViewBag.Setembro[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE OUTUBRO -->

        @{ if (ViewBag.Outubro.Count == 0)
            {
                <tr>
                    <td align="center">OUTUBRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Outubro.Count; i++)
            {
                var total = ViewBag.Outubro.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">OUTUBRO</td>
                    }
                    <td>@ViewBag.Outubro[i].Cliente</td>
                    <td>@ViewBag.Outubro[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE NOVEMBRO -->

        @{ if (ViewBag.Novembro.Count == 0)
            {
                <tr>
                    <td align="center">NOVEMBRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Novembro.Count; i++)
            {
                var total = ViewBag.Novembro.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">NOVEMBRO</td>
                    }
                    <td>@ViewBag.Novembro[i].Cliente</td>
                    <td>@ViewBag.Novembro[i].Valor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Dezembro -->

        @{ if (ViewBag.Dezembro.Count == 0)
            {
                <tr>
                    <td align="center">DEZEMBRO</td>
                    <td colspan="2" align="center"><font color="red">NÃO HÁ REGISTRO</font></td>
                </tr>
            }
            for (int i = 0; i < ViewBag.Dezembro.Count; i++)
            {
                var total = ViewBag.Dezembro.Count;

                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">DEZEMBRO</td>
                    }
                    <td>@ViewBag.Dezembro[i].Cliente</td>
                    <td>@ViewBag.Dezembro[i].Valor</td>
                </tr>
                cont++;
            }
        }
</table>
<br />

Envolti Teste - Danielle/Malwee/Malwee/Views/Estatisticas/FornecedorSemAtendimentoNoMes.cshtml
@{
    ViewBag.Title = "FornecedorSemAtendimentoNoMes";
    int cont = 0;
}

<h2>Fornecedor Sem Atendimento Por Mes</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th>Mês</th>
            <th>FORNECEDOR</th>
        </tr>
    </thead>
    <tbody>
        <!-- REGISTRO DO MES DE JANEIRO -->
        @{

            for (int i = 0; i < ViewBag.Janeiro.Count; i++)
            {
                var total = ViewBag.Janeiro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JANEIRO</td>
                    }
                    <td>@ViewBag.Janeiro[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }

        <!-- REGISTRO DO MES DE FEVEREIRO -->
        @{


            for (int i = 0; i < ViewBag.Fevereiro.Count; i++)
            {
                var total = ViewBag.Fevereiro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">FEVEREIRO</td>
                    }
                    <td>@ViewBag.Fevereiro[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }

        <!-- REGISTRO DO MES DE MARCO -->

        @{
            for (int i = 0; i < ViewBag.Marco.Count; i++)
            {
                var total = ViewBag.Marco.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">MARÇO</td>
                    }

                    <td>@ViewBag.Marco[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Abril -->

        @{
            for (int i = 0; i < ViewBag.Abril.Count; i++)
            {
                var total = ViewBag.Abril.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">ABRIL</td>
                    }

                    <td>@ViewBag.Abril[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE MAIO -->

        @{
            for (int i = 0; i < ViewBag.Maio.Count; i++)
            {

                var total = ViewBag.Maio.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">MAIO</td>
                    }
                    <td>@ViewBag.Maio[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE JUNHO -->

        @{
            for (int i = 0; i < ViewBag.Junho.Count; i++)
            {

                var total = ViewBag.Junho.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JUNHO</td>
                    }
                    <td>@ViewBag.Junho[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Julho -->

        @{
            for (int i = 0; i < ViewBag.Julho.Count; i++)
            {

                var total = ViewBag.Julho.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">JULHO</td>
                    }
                    <td>@ViewBag.Julho[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE AGOSTO -->

        @{
            for (int i = 0; i < ViewBag.Agosto.Count; i++)
            {

                var total = ViewBag.Agosto.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">AGOSTO</td>
                    }
                    <td>@ViewBag.Agosto[i].Fornecedor</td>

                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Setembro -->

        @{
            for (int i = 0; i < ViewBag.Setembro.Count; i++)
            {

                var total = ViewBag.Setembro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">SETEMBRO</td>
                    }
                    <td>@ViewBag.Setembro[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE OUTUBRO -->

        @{
            for (int i = 0; i < ViewBag.Outubro.Count; i++)
            {
                var total = ViewBag.Outubro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">OUTUBRO</td>
                    }
                    <td>@ViewBag.Outubro[i].Fornecedor</td>
                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE NOVEMBRO -->

        @{
            for (int i = 0; i < ViewBag.Novembro.Count; i++)
            {

                var total = ViewBag.Novembro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">NOVEMBRO</td>
                    }
                    <td>@ViewBag.Novembro[i].Fornecedor</td>

                </tr>
                cont++;
            }
        }
        <!-- REGISTRO DO MES DE Dezembro -->

        @{
            for (int i = 0; i < ViewBag.Dezembro.Count; i++)
            {

                var total = ViewBag.Dezembro.Count;
                <tr>
                    @if (i == 0)
                    {
                        <td rowspan="@total" align="center">DEZEMBRO</td>
                    }
                    <td>@ViewBag.Dezembro[i].Fornecedor</td>

                </tr>
                cont++;
            }
        }
</table>
<br />

Envolti Teste - Danielle/Malwee/Malwee/Views/Estatisticas/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>CLIQUE NO LINK PARA VISUALIZAR</h2>
<div>    
    @Html.ActionLink("Os 3 clientes que mais gastaram em serviços por mês no ano atual ", "ClienteMaisGastaramMes", "Estatisticas", new { area = "" }, new { @class = "navbar-brand" })
</div>
<div>
    @Html.ActionLink("Lista de fornecedores sem prestar atendimento por mês no ano atual  ", "FornecedorSemAtendimentoNoMes", "Estatisticas", new { area = "" }, new { @class = "navbar-brand" })
</div>
<br />